import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, Email, To, Content

def build_html_body(results: dict[str, str], source_title: str, lang: str = "en") -> str:
    badge_map = {
        "twitter": ("#1DA1F2", "🐦 Twitter / X"),
        "linkedin": ("#0A66C2", "💼 LinkedIn"),
        "facebook": ("#1877F2", "📘 Facebook"),
        "instagram": ("#E4405F", "📸 Instagram"),
        "tiktok": ("#000000", "🎵 TikTok"),
    }

    direction = "rtl" if lang == "ar" else "ltr"
    align = "right" if lang == "ar" else "left"

    title_text = "Your Generated Posts Are Ready!" if lang == "en" else "منشوراتك جاهزة!"
    subtitle_text = f"Based on: {source_title}" if source_title else (
        "Here are your platform-optimized posts." if lang == "en" else "إليك منشوراتك المخصصة لكل منصة."
    )

    posts_html = ""
    for platform, content in results.items():
        color, label = badge_map.get(platform, ("#666", platform))
        posts_html += f"""
        <div style="background:#f8f9fa; border-radius:12px; padding:20px; margin-bottom:20px; border-left:4px solid {color}; direction:{direction}; text-align:{align};">
            <span style="display:inline-block; background:{color}; color:white; padding:4px 14px; border-radius:20px; font-size:13px; font-weight:bold; margin-bottom:10px;">{label}</span>
            <p style="font-size:15px; line-height:1.7; color:#333; white-space:pre-wrap;">{content}</p>
        </div>
        """

    return f"""
    <html dir="{direction}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://fonts.googleapis.com/css2?family=Tajawal:wght@400;700&display=swap" rel="stylesheet">
    </head>
    <body style="font-family:'Segoe UI',Tajawal,sans-serif; background:#f4f4f6; margin:0; padding:0;">
        <div style="max-width:600px; margin:30px auto; background:white; border-radius:16px; overflow:hidden; box-shadow:0 2px 12px rgba(0,0,0,0.08);">
            <div style="background:linear-gradient(135deg,#0066cc,#004080); padding:30px; text-align:center;">
                <h1 style="color:white; margin:0; font-size:24px;">🚀 {title_text}</h1>
                <p style="color:#cce5ff; margin:8px 0 0; font-size:15px;">{subtitle_text}</p>
            </div>
            <div style="padding:25px;">
                {posts_html}
            </div>
            <div style="background:#f8f9fa; padding:20px; text-align:center; border-top:1px solid #e0e0e0;">
                <p style="color:#888; font-size:12px; margin:0;">
                    {("Generated by ContentMultiplier AI" if lang == "en" else "تم التوليد بواسطة مضاعف المحتوى AI")}
                </p>
            </div>
        </div>
    </body>
    </html>
    """

def send_results_email(to_email: str, results: dict[str, str], source_title: str = "", lang: str = "en") -> bool:
    api_key = os.getenv("SENDGRID_API_KEY")
    from_email = os.getenv("SENDGRID_FROM_EMAIL", "noreply@contentmultiplier.app")

    if not api_key:
        return False

    subject = "Your Posts Are Ready! 🚀" if lang == "en" else "منشوراتك جاهزة! 🚀"
    html_content = build_html_body(results, source_title, lang)

    message = Mail(
        from_email=Email(from_email),
        to_emails=To(to_email),
        subject=subject,
        html_content=Content("text/html", html_content),
    )

    try:
        sg = SendGridAPIClient(api_key)
        response = sg.send(message)
        return response.status_code in (200, 201, 202)
    except Exception:
        return False

def send_welcome_email(to_email: str, name: str, referral_code: str | None = None, lang: str = "en") -> bool:
    api_key = os.getenv("SENDGRID_API_KEY")
    from_email = os.getenv("SENDGRID_FROM_EMAIL", "noreply@contentmultiplier.app")
    if not api_key:
        return False

    direction = "rtl" if lang == "ar" else "ltr"
    subject = "Welcome to ContentMultiplier AI! 🚀" if lang == "en" else "مرحباً بك في مضاعف المحتوى! 🚀"
    greeting = f"Hi {name}!" if lang == "en" else f"مرحباً {name}!"
    intro = "Welcome to ContentMultiplier AI. Here's how to get started:" if lang == "en" else "مرحباً بك في مضاعف المحتوى. إليك خطوات البداية:"
    step1 = "1. Paste any article URL or text" if lang == "en" else "١. الصق رابط أي مقال أو نص"
    step2 = "2. Choose your platforms (Twitter, LinkedIn, Facebook, etc.)" if lang == "en" else "٢. اختر المنصات (تويتر، لينكدإن، فيسبوك...)"
    step3 = "3. Select tone and language" if lang == "en" else "٣. اختر النبرة واللغة"
    step4 = "4. Get platform-optimized posts in seconds!" if lang == "en" else "٤. استلم منشورات مخصصة خلال ثوانٍ!"
    trial = "You get 5 free generations daily. Upgrade anytime for unlimited access." if lang == "en" else "لديك 5 توليدات مجانية يومياً. يمكنك الترقية في أي وقت."

    ref_html = ""
    if referral_code:
        ref_text = "Your referral link (invite friends & earn free months):" if lang == "en" else "رابط الإحالة الخاص بك (ادعُ أصدقاءك واربح أشهراً مجانية):"
        ref_url = f"https://contentmultiplier.app/ref/{referral_code}"
        ref_html = f"""
        <div style="background:#e8f5e9; border-radius:12px; padding:15px; margin:20px 0; direction:{direction};">
            <p style="margin:0 0 8px; font-weight:bold;">🎁 {ref_text}</p>
            <code style="background:white; padding:8px 12px; border-radius:8px; font-size:14px;">{ref_url}</code>
        </div>
        """

    html = f"""
    <html dir="{direction}">
    <head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
    <body style="font-family:'Segoe UI',Tajawal,sans-serif; background:#f4f4f6; margin:0; padding:0;">
        <div style="max-width:600px; margin:30px auto; background:white; border-radius:16px; overflow:hidden; box-shadow:0 2px 12px rgba(0,0,0,0.08);">
            <div style="background:linear-gradient(135deg,#0066cc,#004080); padding:30px; text-align:center;">
                <h1 style="color:white; margin:0; font-size:24px;">🚀 {subject}</h1>
            </div>
            <div style="padding:25px; direction:{direction}; text-align:{('right' if lang == 'ar' else 'left')};">
                <h2>{greeting}</h2>
                <p>{intro}</p>
                <ol style="line-height:2; font-size:15px;">
                    <li>{step1}</li>
                    <li>{step2}</li>
                    <li>{step3}</li>
                    <li>{step4}</li>
                </ol>
                <p style="color:#666;">{trial}</p>
                {ref_html}
                <p style="margin-top:30px;">{'Happy content multiplying! 🚀' if lang == 'en' else 'توليد موفق! 🚀'}</p>
                <p>{'The ContentMultiplier Team' if lang == 'en' else 'فريق مضاعف المحتوى'}</p>
            </div>
        </div>
    </body>
    </html>
    """

    message = Mail(from_email=Email(from_email), to_emails=To(to_email), subject=subject, html_content=Content("text/html", html))
    try:
        sg = SendGridAPIClient(api_key)
        response = sg.send(message)
        return response.status_code in (200, 201, 202)
    except Exception:
        return False

def send_subscription_activated_email(to_email: str, name: str, plan: str, referral_code: str | None = None, lang: str = "en") -> bool:
    api_key = os.getenv("SENDGRID_API_KEY")
    from_email = os.getenv("SENDGRID_FROM_EMAIL", "noreply@contentmultiplier.app")
    if not api_key:
        return False

    direction = "rtl" if lang == "ar" else "ltr"
    plan_names = {"basic": "Basic ($9/mo)" if lang == "en" else "أساسي ($9/شهر)", "pro": "Pro ($29/mo)" if lang == "en" else "احترافي ($29/شهر)"}
    plan_name = plan_names.get(plan, plan)
    subject = "Subscription Activated! 🎉" if lang == "en" else "تم تفعيل اشتراكك! 🎉"
    heading = f"Thank you, {name}!" if lang == "en" else f"شكراً لك، {name}!"
    msg = f"Your {plan_name} plan is now active." if lang == "en" else f"باقتك {plan_name} مفعلة الآن."
    benefit = "You can now generate more posts, access all platforms, and use all tones." if lang == "en" else "يمكنك الآن توليد المزيد من المنشورات، واستخدام جميع المنصات والنبرات."
    referral_url = f"https://contentmultiplier.app/ref/{referral_code}" if referral_code else None

    ref_html = ""
    if referral_url:
        ref_text = "Share your referral link and earn a free month for each friend who subscribes:" if lang == "en" else "شارك رابط الإحالة واربح شهراً مجانياً لكل صديق يشترك:"
        ref_html = f"""
        <div style="background:#e8f5e9; border-radius:12px; padding:15px; margin:20px 0; direction:{direction};">
            <p style="margin:0 0 8px; font-weight:bold;">🎁 {ref_text}</p>
            <code style="background:white; padding:8px 12px; border-radius:8px; font-size:14px;">{referral_url}</code>
        </div>
        """

    html = f"""
    <html dir="{direction}">
    <head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
    <body style="font-family:'Segoe UI',Tajawal,sans-serif; background:#f4f4f6; margin:0; padding:0;">
        <div style="max-width:600px; margin:30px auto; background:white; border-radius:16px; overflow:hidden; box-shadow:0 2px 12px rgba(0,0,0,0.08);">
            <div style="background:linear-gradient(135deg,#00d4aa,#008970); padding:30px; text-align:center;">
                <h1 style="color:white; margin:0; font-size:24px;">🎉 {subject}</h1>
            </div>
            <div style="padding:25px; direction:{direction}; text-align:{('right' if lang == 'ar' else 'left')};">
                <h2>{heading}</h2>
                <p style="font-size:16px;">{msg}</p>
                <p>{benefit}</p>
                {ref_html}
                <p style="margin-top:30px;">{'Happy multiplying! 🚀' if lang == 'en' else 'توليد موفق! 🚀'}</p>
                <p>{'The ContentMultiplier Team' if lang == 'en' else 'فريق مضاعف المحتوى'}</p>
            </div>
        </div>
    </body>
    </html>
    """

    message = Mail(from_email=Email(from_email), to_emails=To(to_email), subject=subject, html_content=Content("text/html", html))
    try:
        sg = SendGridAPIClient(api_key)
        response = sg.send(message)
        return response.status_code in (200, 201, 202)
    except Exception:
        return False
